# Generated by Django 5.1.3 on 2024-12-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='included',
            field=models.TextField(blank=True, help_text='Что включено в тур', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='not_included',
            field=models.TextField(blank=True, help_text='Что не включено в тур', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='route',
            field=models.TextField(blank=True, help_text='Маршрут тура', null=True),
        ),
    ]
