# Generated by Django 5.1.3 on 2024-12-11 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_image_tour_included_tour_not_included_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='operator_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tour',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
