# Generated by Django 5.1.3 on 2024-12-12 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_booking_operator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Средний рейтинг'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='tours.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
