# Generated by Django 5.1.3 on 2024-12-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_image_remove_tour_image_tour_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='images',
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
